openapi: 3.0.3
info:
  title: BlaBla - OpenAPI 3.0
  description: blabla api
  version: 1.0.11
servers:
  - url: http://localhost:8080
paths:
  /order:
    get:
      operationId: get order
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'

  /location:
    get:
      operationId: find location like
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            minimum: 3
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationResponse'

  /login/request-auth/{phone}:
    post:
      operationId: sendLoginInfo
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'

  /login/confirm-auth/{phone}:
    post:
      operationId: confirmAuth
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmAuthRequest'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmAuthResponse'

  /user/info/{phone}:
    put:
      operationId: updateUserInfo
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
    get:
      operationId: getUserInfo
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'

  /user/notifications/{phone}:
    put:
      operationId: updateUserNotificationsInfo
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserNotificationsDto'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNotificationsDto'
    get:
      operationId: getUserNotificationsInfo
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNotificationsDto'

  /user/info/avatar/{phone}:
    put:
      operationId: userSetAvatar
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAvatarDto'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAvatarDto'
    get:
      operationId: userGetAvatar
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAvatarDto'
    delete:
      operationId: userDeleteAvatar
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAvatarDto'

  /user/phone/{phone}:
    put:
      operationId: updatePhoneNumber
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'

components:
  schemas:

    InfoResponse:
      properties:
        time:
          type: string
        message:
          type: string

    UserAvatarDto:
      properties:
        data:
          type: string
          format: byte

    UserNotificationsDto:
      properties:
        email:
          type: string
          pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$
        newMembers:
          type: boolean
        statusChanging:
          type: boolean

    UserDto:
      properties:
        username:
          type: string
          maxLength: 255
        birthday:
          type: string
          format: date
          pattern: (0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[1,2])-(19|20)\d{2}
        aboutMe:
          type: string
          maxLength: 1000

    LocationResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LocationItem'

    ConfirmAuthRequest:
      required:
        - confirmation_sequence
      type: object
      properties:
        confirmation_sequence:
          type: string

    LocationItem:
      properties:
        id:
          type: string
          format: uuid
        address:
          type: string

    ConfirmAuthResponse:
      properties:
        status:
          $ref: '#/components/schemas/AuthResponseStatus'
        descr:
          type: string
          description: Описание ответа

    DefaultResponse:
      properties:
        status:
          $ref: '#/components/schemas/DefaultResponseStatus'
        descr:
          type: string
          description: Описание ответа

    AuthResponseStatus:
      enum:
        - SUCCESS
        - NEW_USER
        - WRONG_CODE

    DefaultResponseStatus:
      enum:
        - SUCCESS
        - ERROR