openapi: 3.0.3
info:
  title: BlaBla - OpenAPI 3.0
  description: blabla api
  version: 1.0.11
servers:
  - url: http://localhost:8080
paths:
  /order:
    get:
      operationId: get order
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'

  /location:
    get:
      operationId: find location like
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            minimum: 3
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationResponse'

  /login/request-auth:
    post:
      operationId: sendLoginInfo
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'

  /login/confirm-auth:
    post:
      operationId: confirmAuth
      parameters:
        - name: phone
          in: path
          required: true
          schema:
            pattern: ^(\+7|8|7)(\d{10})$
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmAuthRequest'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'



components:
  schemas:
    InfoResponse:
      properties:
        time:
          type: string
        message:
          type: string

    LocationResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LocationItem'

    ConfirmAuthRequest:
      required:
        - confirmation_sequence
      type: object
      properties:
        confirmation_sequence:
          type: string

    LocationItem:
      properties:
        id:
          type: string
          format: uuid
        address:
          type: string

    DefaultResponse:
      properties:
        status:
          $ref: '#/components/schemas/DefaultResponseStatus'
        descr:
          type: string
          description: Описание ответа

    DefaultResponseStatus:
      enum:
        - SUCCESS
        - ERROR