openapi: 3.0.3
info:
  title: BlaBla - OpenAPI 3.0
  description: blabla api
  version: 1.0.11
servers:
  - url: http://localhost:8080
paths:
  /order:
    get:
      operationId: get order
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
      security:
        - petstore_auth:
            - write:pets
            - read:pets

components:
  schemas:
    InfoResponse:
      properties:
        time:
          type: string
        message:
          type: string