spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: liquibase/changelog-master.xml
  jpa:
    show-sql: true
